baseURL: https://keenanroe.netlify.app/
languageCode: en-us
summaryLength: '10'
theme: kross-hugo
title: Keenan Roe
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  author: Keenan Roe
  baidu_analytics_id: ''
  baidu_site_verification: ''
  copyright: Copyright &copy; 2021 a Theme by [Gethugothemes](https://gethugothemes.com)
  description: This is meta description
  email: kroe4@uic.edu
  phone: (217)-220-3097
  address: 1907 W Wilson Ave. Apt. 2B, Chicago IL 60640
  google_analytics_id: ''
  home: Home
  logo: ''
  map:
    enable: yes
    gmap_api: https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en
    map_latitude: '51.5223477'
    map_longitude: '-0.1622023'
    map_marker: images/marker.png
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/slick/slick.css
      - link: plugins/themify-icons/themify-icons.css
    js:
      - link: plugins/jQuery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/shuffle/shuffle.min.js
      - link: plugins/google-map/map.js
  preloader:
    enable: yes
    preloader: images/preloader.gif
  social:
    - email: kroe4@uic.edu
      icon: ti-email
    - URL: 'https://www.linkedin.com/in/keenan-roe-128961220/'
      icon: ti-linkedin
    - URL: 'https://github.com/Keenan-Roe'
      icon: ti-github
  theme_color: '#41228e'
menu:
  main:
    - URL: about
      name: About
      weight: 1
    - URL: resume
      name: Resume
      weight: 2
    - URL: portfolio
      name: Portfolio
      weight: 3
    - URL: contact
      name: Contact
      weight: 4
